### ISSUE TITLE
PIN task globally

### ISSUE THREAD

**Issue by DRYN07** [jjw24/Wox.Plugin.Todos#4]
Is it possible to pin the task to the top globally? I would like to see the task every time I open flow launcer. This would be very helpful.

**Comment by jjw24** [comment]
So flow doesn't have the mechanism to display results(tasks) on startup.

Next best change would be to allow plugin to pin an ordered task list that displays when its action hotkey is triggered. I can't make any promises this feature will be added any time soon due to my other commitments. I will keep it on the to do list for this plugin.

**Comment by jjw24** [comment]
Issue transferred to new repo.
